### ISSUE TITLE
Can prepare cards that aren't in your hand when you go to play

### ISSUE THREAD

**Issue by hwoodward** [hwoodward/Remote-Card-Games#63] opened 2019-12-07 04:39 UTC
**Describe the bug**
You can have a set of prepared cards that includes cards that aren't in your hand (or includes cards in your hand twice). When you go to play this causes and error that can crash the game if not caught.

**To Reproduce**
1. Prepare a card you don't have duplicate of
2. Discard that card
3. Try to play prepared cards
Alternately
1. Prepare all of a certain card value in your hand
2. Prepare those cards AGAIN
3. Try to play prepared cards

in both cases the game crashes

**Expected behavior**
We should both not be able to prepare cards twice AND should simply display an error message if you do not have all the prepared cards you are trying to play in your hand - not crash.

**Additional context**
Some of this may be handled in enforceRules already, if not error handling for this should be included.

**Comment by hwoodward** [comment] 2019-12-07 04:42
3 Things to do about this:
1. ERROR HANDLING FOR PLAY CARDS (as part of enforceRules branch)
2. Prevent double preparation. Once prepared, deselect, and when preparing cards consider checking they are not already prepared (I know we were going to track that for highlight purposes?)
3. Consider preventing discarding prepared cards. We could check for prepared in discard logic? (again relies on having the cards marked as prepared in the UI). We could consider a message during confirm such as "are you sure you want to discard <>, you have cards of this category prepared/played" 

2 and 3 are optional and may merit a feedback cycle.

**Comment by slwoodward** [comment] 2019-12-07 06:05
Possible solution: I can alter GUI so that you cannot "select" a card that has been prepared.  This should prevent preparing card twice and discarding a prepared card.

**Comment by slwoodward** [comment] 2019-12-22 21:58
Fixed with issue 73.

**Comment by slwoodward** [comment] 2019-12-22 22:05
While it no longer crashes, the display can get messed up as the wrong clickable image might be removed from the current hand, so if you discard the duplicate of a prepared card, the prepared card will disappear, but the selected card will still be present.  Need to modify logic so that clickable image that is removed (either because card is played or discarded) is the intended one.

**Comment by hwoodward** [comment] 2020-01-27 18:05
I think the new issue is a different bug - its no longer performing an illegal action and error but the UI display is misleading, the current bug title is confusing

**Closed** 2020-01-27 23:08 UTC
Labels: bug
